### ISSUE TITLE
Transaction problems

### ISSUE THREAD

**Issue by nosmo** [equalitie/RVD-webapp#4]
I'm not sure what causes this, but the app got stuck returning nothing but the following, refusing to access MySQL otherwise: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/RVD-webapp/rvd/views/login.py", line 14, in login
    if helpers.validate_form_on_submit(login_form):
  File "/usr/local/lib/python2.7/dist-packages/flask_admin/helpers.py", line 66, in validate_form_on_submit
    return is_form_submitted() and form.validate()
  File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 200, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 220, in _run_validation_chain
    validator(form, self)
  File "/opt/RVD-webapp/rvd/forms/Login.py", line 25, in validate_password
    result = session.query(User).filter(and_(User.email == self.login.data, User.password == field.data)).one()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2398, in one
    ret = list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2441, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2456, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1005, in _execute_context
    None, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 999, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 354, in _revalidate_connection
    "Can't reconnect until invalid "
StatementError: Can't reconnect until invalid transaction is rolled back (original cause: InvalidRequestError: Can't reconnect until invalid transaction is rolled back) u'SELECT users.id AS users_id, user
s.email AS users_email, users.password AS users_password, users.organisation_id AS users_organisation_id, users.is_admin AS users_is_admin \nFROM users \nWHERE users.email = %s AND users.password = %s' [i
mmutabledict({})]
```

This could be related to the use of Session objects in MySQL based on a cursory Google but I'm afraid all I did for this issue is restart the app due to an urgent need for it to be operational. I'm sorry I can't offer more context.

**Comment by l-r** [comment]
I'm pretty confident this is because data is not flushed properly to the DB (though apparently committed). Normally the session should flush automatically after a transaction, but it doesn't seem to work as intended, so this will require a bit of digging.

**Comment by l-r** [comment]
I don't have a definitive answer here, but after a bit of searching, I found this to be most helpful: http://stackoverflow.com/questions/23301968/invalid-transaction-persisting-across-requests

We currently commit transactions to the DB manually, pretty much after every form gathering method, which I think is making our lives harder than it should. I'll move the session committing to a request teardown handler - since the app is really simple and should generally do a single action per request anyways. Then we should we able to at least catch errors in a single place and rollback when needed.

There needs to be some pretty serious refactoring of the views anyways :)
